name: Build Image

on:

  workflow_dispatch:

  push:
    tags:
      - 'v*'  

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Load .build_env
        uses: aarcangeli/load-dotenv@v1
        with:
          filenames: |
            ${{ env.BUILD_ENV_FILE }}
          quiet: 'false'
          if-file-not-found: 'error'
          expand: 'false'
        if: env.BUILD_ENV_FILE != ''
          
      - name: Set Additional Environment Variables and Output
        id: vars
        run: |
          # set APP_BUILD_DATE
          echo "APP_BUILD_DATE=$(date +%F-%s)" >> "$GITHUB_ENV"
        if: true
      
      - name: Create Image Tags and Labels
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            name=hobbit00378/izpbx-asterisk,enable=true
            name=ghcr.io/hobbit378/izpbx-asterisk,enable=true
          flavor: |
            latest=auto
            prefix=
            suffix=
          tags: |
            # set tagged version
            type=semver,pattern={{raw}},event=tag
            type=semver,pattern={{version}},event=tag
            type=semver,pattern={{major}}.{{minor}},event=tag
            type=raw,value=dev-${{ env.APP_VER }},event=workflow_dispatch
          labels: |
            org.opencontainers.image.source=https://github.com/hobbit378/docker-izpbx
            org.opencontainers.image.version="${{env.APP_VER}} (Build: ${{env.APP_VER_BUILD}})" 
      
      - name: Log Values
        run: |
          echo "START Build Arguments"
          echo "${BUILD_ARGS:-na}"
          echo "END Build Arguments"
          # echo "App Version: $APP_VER"
          # echo "Build Number: $APP_VER_BUILD"
          # echo "Build Date: $APP_BUILD_DATE"
          # echo "FreePBX Version: ${FREEPBX_VER:-n/a}"
          # echo "Asterisk Version: ${ASTERISK_VER:-n/a}"
          echo "END OUTPUT"

      - name: Build and Push Image
        uses: docker/build-push-action@v4
        with:
          context: ./izpbx-asterisk/
          build-args: |
            APP_BUILD_DATE=${{ env.APP_BUILD_DATE }}
            ${{ env.BUILD_ARGS }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
        if: env.APP_VER != ''
