name: Build Image

on:

  workflow_dispatch:

  push:
    tags:
      - 'v*'  

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_VER: ${{vars.APP_VER}}
      APP_VER_BUILD: ${{vars.APP_VER_BUILD}}
      APP_BUILD_COMMIT: ${{github.sha}}
      APP_BUILD_DATE: '1970-1-1'
      BUILD_ARGS: ''
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Container Registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ vars.REPO_DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Checkout Code from GitHub Repository
        uses: actions/checkout@v3

      - name: Load ENVARS from File
        uses: aarcangeli/load-dotenv@v1
        with:
          filenames: |
            ${{ vars.APP_ENVARS_FILE }}
          quiet: 'false'
          if-file-not-found: 'error'
          expand: 'false'
        if: vars.APP_ENVARS_FILE != ''
          
      - name: Set Additional Variables 
        id: vars
        run: |
          # set APP_BUILD_DATE
          echo "APP_BUILD_DATE=$(date +%F-%s)" >> "$GITHUB_ENV"
      
      - name: Create Metadata - Image Tags and Labels
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            name=hobbit00378/izpbx-asterisk,enable=true
            name=ghcr.io/hobbit378/izpbx-asterisk,enable=true
          flavor: |
            latest=auto
            prefix=
            suffix=
          tags: |
            # set tagged version
            type=semver,pattern={{version}},event=tag
            type=semver,pattern={{major}}.{{minor}},event=tag
            type=semver,pattern={{major}}.{{minor}}-{{sha}},event=tag
            type=raw,value=${{ env.APP_VER }}-wd-{{sha}},event=workflow_dispatch
          labels: |
            org.opencontainers.image.source=https://github.com/hobbit378/docker-izpbx
            org.opencontainers.image.version="${{env.APP_VER}} (Build: ${{env.APP_VER_BUILD}})" 

      - name: Build and Push Image
        uses: docker/build-push-action@v4
        with:
          context: ./izpbx-asterisk/
          build-args: |
            APP_VER
            APP_VER_BUILD
            APP_BUILD_COMMIT
            APP_BUILD_DATE
            ${{ env.BUILD_ARGS }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ vars.PUSH_ENABLED }}
        if: vars.BUILD_ENABLED
