name: Clear Container Registry

on:
  # every Sunday and Wednesday at 01:30am
  schedule:
    - cron: '30 1 * * 0,3'
  # or manually
  workflow_dispatch:

jobs:
  clear-all:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: 'Clear untagged images '
        uses: dataaxiom/ghcr-cleanup-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package: 'izpbx-asterisk'
          dry-run: false
      - name: 'Clear tagged images without version 20.16* tag'
        uses: dataaxiom/ghcr-cleanup-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package: 'izpbx-asterisk'
          exclude-tags: '20.16*'
          keep-n-tagged: 5
          dry-run: false