name: Clear Container Registry

on:
  
  workflow_dispatch:
  
  schedule:
    - cron: '30 1 * * 0'

jobs:
  clear-all:
    
    runs-on: ubuntu-latest
    permissions:
      packages: write
    
    steps:
      - name: 'Clear untagged images '
        uses: actions/delete-package-versions@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package-name: 'izpbx-asterisk'
          package-type: 'container'
          delete-only-untagged-versions: 'true'

