name: Docker Image CI

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Date
        id: date
        run: echo "::set-output name=date::$(date +%s)"
      
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Create Image Tags and Labels
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/hobbit378/izpbx-asterisk
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch,suffix=-{{sha}}
            type=semver,pattern={{raw}},suffix=-{{sha}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          labels: |
            org.opencontainers.image.tile=izpbx-mwe
            org.opencontainers.image.source=https://github.com/hobbit378/docker-izpbx

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v4
        with:
          context: ./izpbx-asterisk/
          build-args: APP_BUILD_DATE=${{ steps.date.outputs.date }} APP_VER=20.16
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
